import java.util.ArrayList;

import AbstractClass.Tile;
import Game.Lawn;
import Plant.Jalapeno;
import Plant.Peashooter;
import Zombie.NormalZombie;
import Game.Game;
public class Main {
    public static void main(String[] args) {
       
        Lawn lawn = new Lawn();

        lawn.printLawn();
        Game.setSun(500);
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
        lawn.moveAll(); 
        lawn.printLawn();
    }
}
